Name :Nitesh yadav
Roll : S050
PDS 4
Date: 05/08/2026

a. Write a python code to create Numpy Array.

In [29]:
import numpy as np

In [26]:
a = np.array([1,2,3])
print(a)

[1 2 3]


b. Write a python code to demonstrate basic operations on single array.

In [27]:
print(a+3)
print(a*2)


[4 5 6]
[2 4 6]


c. Write a python code to create array with 10 elements and slice element
from 1st to 5th element.

In [38]:
b =np.array([1,2,3,4,5,6,7,8,9,10])
print(b[0:5])

[1 2 3 4 5]


d. Write a python code to sort an array alphabetically.

In [40]:
name =np.array(["Nitesh","Rahul","Amit","Kaushal","Jay"])
print(np.sort(name))

['Amit' 'Jay' 'Kaushal' 'Nitesh' 'Rahul']


e. Write a python code to create a filter array that will return maximum
values from an array.

In [41]:
price=np.array([1000,5005,800,3000,7000])
print(price[price>4000])

[5005 7000]
